platform :ios, '10.0'
use_frameworks!

target 'ios_native_app' do
end

flutter_application_path = '../flutter_common_module'
eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
